[package]
name = "botty"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "*"
toml = "0.4.2"

[dependencies.serenity]
default-features = true
version = "0.10"
